name: Build

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update -y
          sudo apt install -y --no-install-recommends \
            build-essential \
            meson \
            libwayland-dev \
            libcairo-dev \
            libglib2.0-dev \
            libxkbcommon-dev

      - name: Make build directory
        run: mkdir builddir

      - name: Configure
        run: |
          meson setup builddir \
            -Dxwayland=false

      - name: Build
        run: ninja -C builddir
